filegroup(
  name = "model_1",
  srcs = [
    "models/model_1/2/graph.pb",
    "models/model_1/2/graph.onnx",
  ],
  visibility = ["//visibility:public"],
)

filegroup(
  name = "model_2",
  srcs = [
    "models/model_2/1/graph.pb",
    "models/model_2/1/graph.onnx",
  ],
  visibility = ["//visibility:public"],
)

filegroup(
  name = "model_3",
  srcs = [
    "models/model_3/3/graph.pb",
    "models/model_3/3/graph.onnx",
  ],
  visibility = ["//visibility:public"],
)

filegroup(
  name = "files",
  srcs = [
    "files/hello",
  ],
  visibility = ["//visibility:public"],
)
